### ISSUE TITLE
Issues in ADVI tutorial

### ISSUE THREAD

**Issue by v-i-s-h** [TuringLang/docs#347]
First of all I would like the team for these wonderful tutorials; I learned a lot by following them.

While going through the tutorial, I found a few problems with ADVI tutorial. In the section for ADVI in linear regression,
1. `unstandardize()` function is not correctly  rescaling the data back.
2. Because of this, the prediction functions give wrong outputs
3. The plots does not show the error bars properly because of wrong rescaling

Can you confirm whether my observations are correct? In that case, I can open a PR to fix these.

**Comment by shravanngoswamii** [comment]
All tutorials are updated now can you check it again, https://turinglang.org/docs/

**Comment by penelopeysm** [comment]
I think this was probably fixed by https://github.com/TuringLang/docs/pull/426.
