### ISSUE TITLE
Unicode characters not appearing properly

### ISSUE THREAD

**Issue by shravanngoswamii** [TuringLang/docs#442]
Unicode characters are not appearing properly, it's working and executing fine so I guess it's not a Julia issue, maybe it's a Quarto rendering issue!!

I do not know how but I just gave two empty lines before starting the code and it worked!! it also works if I put any HTML comment before the code!!

I am using Quarto Pre-release with `engine: julia`.

I will update this issue later...

edit: This is a random behaviour so if you find any un-rendered characters then please mention them in this issue!

**Comment by Ishahansalpara** [comment]
I guess it's fixed now in the latest version of Quarto!! I can't see any non rendered unicode character in tutorials!!

**Comment by shravanngoswamii** [comment]
Yeah, It's fixed! Thanks for reminding!!
