### ISSUE TITLE
Manifest.toml files are outdated

### ISSUE THREAD

**Issue by penelopeysm** [TuringLang/docs#495]
The `Manifest.toml` files on the master branch still point to 0.32.0 of Turing, which leads to e.g. this `UndefVarError`: https://turinglang.org/docs/tutorials/docs-12-using-turing-guide/#maximum-likelihood-and-maximum-a-posterior-estimates

https://github.com/TuringLang/docs/blob/1f797b78268685c853efb5a32c3c71744152e47b/tutorials/docs-12-using-turing-guide/Manifest.toml#L1882-L1886

I notice that there used to be [a weekly GitHub Action to update the manifests](https://github.com/TuringLang/docs/blob/9e4f6f455eda8d73faf795f9beb632e009e348dc/.github/workflows/UpdateManifests.yml), which was removed as part of #441. So a quick fix would be to re-enable that workflow and run it.

However, I think a more robust solution for the long term would be to:

1. Use a single environment for building all the docs, rather than one environment per notebook. I don't think there is any use case for having separate environments, and even if there _were_ I think that it would not be the right thing to do — it would be very confusing to the user if the code on separate pages could not be run in the same environment.

2. Pin the version of Turing with a `[compat]` block in the `Project.toml` file (on both the master and backport branches)

3. In the main documentation workflow (using `on: push`), add a check to make sure that the version of Turing specified in `Project.toml` matches the version specified in `_quarto.yml`

4. ~~Gitignore the manifest, only regenerating it when building the docs. IMO it makes more sense to let Julia resolve to the latest compatible versions (e.g. in order to use the latest bugfix version of Turing; and after all, a user reading the docs and running the code is, in all likelihood, going to fetch the latest versions anyway instead of looking for the manifest in this repo). Also, this spares us this issue of having to update the manifest when a new version of Turing is released.~~

Overall, this proposal means that when a new version of Turing is launched, only three files (`_quarto.yml`, `Project.toml`, and `Manifest.toml`) need to be changed; and GitHub will tell you right away if you forget to change one of them. (Of course, the list of old versions will also need to be updated, but that is a separate matter, unrelated to this issue.)

**Comment by penelopeysm** [comment]
I've done (1), (2), and (4) in a branch (https://github.com/TuringLang/docs/tree/pysm/building-docs), happy to work on (3) and put in a PR if this makes sense.

**Comment by devmotion** [comment]
I'm not sure about (1). The problem with a single environment is that it contains many dependencies, and in particular pulls in the SciML stack, even though for most examples only a few dependencies are needed. This bloated environment leads to unnecessarily long precompilation and it is easy run into version conflicts of dependencies, which holds back dependencies to unnecessarily old versions or make them completely incompatible. So the reason for the individual environments is basically the same as for the general recommendation in Julia to use project-specific environments instead of the global environment.

**Comment by penelopeysm** [comment]
@devmotion Sorry for the slow reply! I've been travelling most of last week.

> This bloated environment leads to unnecessarily long precompilation

That's what I had feared, but building the entire set of docs is actually faster with a single env. I couldn't tell you why, but [here it is 1 hr 44 min with a single env](https://github.com/TuringLang/docs/actions/runs/10131613167/job/28014548724?pr=497) and the last build on master with separate envs was 2 hr 8 min](https://github.com/TuringLang/docs/actions/runs/10101428546/job/27934996523).

In the case where someone is developing locally and editing only one notebook, it's true that that precompilation will take longer, but I think that time is negligible compared to the time required to run the examples in most pages of the docs. Precompilation for the single large env takes 10 secs on my M1 MacBook Pro.

> it is easy run into version conflicts of dependencies, which holds back dependencies to unnecessarily old versions or make them completely incompatible

Browsing the logs I don't think this is a major problem yet. I do recognise that it's a drawback!

The flip side is that having a single env ensures that there there is consistency between all parts of the docs. If each page has its own env, then the result of running the same function could potentially be different on different pages. I don't know if this is a problem in practice either — I'd suspect not, but in principle I don't like the possibility of that.

> the general recommendation in Julia to use project-specific environments instead of the global environment

I agree, but I think it comes down to whether we treat each individual notebook as a project, or the entire documentation as a project. I'd vote for the latter, but am open to being convinced otherwise.

In any case, I'll work on adding a check to ensure consistency between the `quarto.yml` and `Project.toml` (or `Project.toml`s if we stick to multiple envs).

**Comment by devmotion** [comment]
> That's what I had feared, but building the entire set of docs is actually faster with a single env. I couldn't tell you why, but [here it is 1 hr 44 min with a single env](https://github.com/TuringLang/docs/actions/runs/10131613167/job/28014548724?pr=497) and [the last build on master with separate envs was 2 hr 8 min](https://github.com/TuringLang/docs/actions/runs/10101428546/job/27934996523).

I assume this could be caused by different environments using different versions of the same package (which increases the number of packages that have to be precompiled). On CI, I think generally you would want to cache packages, artifacts, precompilation cache etc. (using e.g. https://github.com/julia-actions/cache) - then installation and precompilation should be much faster and only be triggered for new package versions.

**Comment by willtebbutt** [comment]
I don't have a strong opinion on this because I've not done it a lot. I'm also concerned about having a single massive environment, for the same reason as @devmotion, but I'm not opposed to giving it a go and seeing how it pans out (I can definitely see the advantages).

**Comment by penelopeysm** [comment]
Okay, the PR #497 now uses a single big env. It's just a PR, of course, so things can be changed if we decide against it; but right now I sense that the balance is very slightly in favour of single-env over multi-env.

I suggested gitignoring the Manifest.toml above, but I'm having second thoughts about that right now. Opinions on that bit are welcome! — if we keep the Manifest.toml file to ease code reproduction, I would just have to add another check in the GHA to make sure that the version of Turing is also up to date with the latest GitHub release.
