### ISSUE TITLE
Inconsistent list of tutorials

### ISSUE THREAD

**Issue by mhauru** [TuringLang/docs#498]
A different list of tutorials is included in the left navigation panel depending on which tutorial page one is looking at. Compare e.g.
https://turing.ml/dev/tutorials/09-variational-inference/ and https://turing.ml/dev/tutorials/10-bayesian-differential-equations/

**Comment by shravanngoswamii** [comment]
You are on old website, we have no access to `turing.ml` domain! Our updated website is here: https://turinglang.org, You can have these tutorials here https://turinglang.org/docs/tutorials/09-variational-inference/ and https://turinglang.org/docs/tutorials/10-bayesian-differential-equations/

We tried all possible things to remove turing.ml, but I think we have to wait until domain expiries, we also have an issue regarding this, see https://github.com/TuringLang/turinglang.github.io/issues/59

**Comment by mhauru** [comment]
My bad!
