### ISSUE TITLE
Replace `Tracker` with `Mooncake` in Bayesian neural networks example

### ISSUE THREAD

**Issue by yebai** [TuringLang/docs#521]
Let's depreciate the support for `Tracker` (we mention `Tracker`in various autodiff doc pages) since it is no longer actively maintained and is known to be problematic for some Bijectors.

**Comment by penelopeysm** [comment]
Also need to mention Mooncake in the main AD page: https://turinglang.org/docs/tutorials/docs-10-using-turing-autodiff/
