### ISSUE TITLE
Use meta variables for all doc URLs to avoid obsolete links 

### ISSUE THREAD

**Issue by yebai** [TuringLang/docs#524]
Let us create a Quarto meta variable for each doc page in a similar way to: 

https://github.com/TuringLang/docs/blob/20209fe4bed0b6fffc7b9c3d8941dd4ce9fb0d6d/_quarto.yml#L163-L164

Usage example:  https://github.com/TuringLang/docs/blob/20209fe4bed0b6fffc7b9c3d8941dd4ce9fb0d6d/404.qmd#L7

to avoid the fragility of relative URLs when renaming and moving doc pages.

**Comment by beingPro007** [comment]
Assign this to me...

**Comment by beingPro007** [comment]
Is this issue part of Hacktoberfest 2024?

**Comment by mhauru** [comment]
@beingPro007, yes, the whole repository is open for Hacktoberfest contributions.
