### ISSUE TITLE
Quarto doesn't complain if examples error

### ISSUE THREAD

**Issue by penelopeysm** [TuringLang/docs#525]
Right now Quarto doesn't complain / exit with an error if any of the code examples return an error. which leads to things like https://turinglang.org/docs/tutorials/03-bayesian-neural-network/. Probably related to the use of the new Julia engine

It's not immediately obvious how to fix this, because maybe sometimes we _do_ want the error.

I can look into it.

**Comment by penelopeysm** [comment]
The culprit is in this metadata file, which is applied to all qmd files under `tutorials`:

https://github.com/TuringLang/docs/blob/364d361d9a74d70baa95c82635cf4716d66c18ac/tutorials/_metadata.yml#L6-L9

Specifically `error: true`.

We should remove this and specifically add it to places where we expect errors.

**Comment by shravanngoswamii** [comment]
> Specifically `error: true`.

I think we added that because we were having a lot of errors and warnings when we were moving the site to Quarto. It's always good to remove it or make it false so that we don't push any defected code into the docs.
