### ISSUE TITLE
Tutorial 'Bayesian Neural Network' Errors on Published Site: `StatefulLuxLayer not defined`

### ISSUE THREAD

**Issue by patrickm663** [TuringLang/docs#531]
Hi

I have noticed the output in the BNN tutorial is erroring out as soon as `StatefulLuxLayer` is introduced:

![image](https://github.com/user-attachments/assets/1718b685-3e7e-4111-9ee6-c541a6ef1fca)

This impacts v0.34.

Regards
Patrick

**Comment by penelopeysm** [comment]
Hi @patrickm663 thanks for reporting! Ahh, https://github.com/TuringLang/docs/pull/529 was supposed to have fixed uncaught errors like these, but I think what happened was that Quarto cached the results and didn't rerun them when that PR was merged. Anyway, I'll look into this one.

**Comment by penelopeysm** [comment]
The correct invocation for this line should be

```julia
const nn = StatefulLuxLayer{true}(nn_initial, nothing, st)
```

I've tested on Julia 1.10.5, macOS, Turing@0.34.1, Lux@1.0.5 and the code runs fine. I can't get it to work via Quarto yet (and I have no idea why), but just thought to post in case this is holding you up.

**Comment by patrickm663** [comment]
Thanks very much for your help!
