### ISSUE TITLE
Broken link to core functionality.

### ISSUE THREAD

**Issue by nfortescue** [TuringLang/docs#534]
The link to in "The next page on [Turing’s core functionality](https://turinglang.org/tutorials/docs-12-using-turing-guide) explains the basic features of the Turing language. From there, you can either look" links to 

https://turinglang.org/tutorials/docs-12-using-turing-guide

This gives a 404. But the link at the bottom of the page to 

https://turinglang.org/docs/tutorials/docs-12-using-turing-guide/

succeeds.  I think the link needs updating

**Comment by penelopeysm** [comment]
Thanks for reporting @nfortescue!
