### ISSUE TITLE
Cache _freeze folder more intelligently

### ISSUE THREAD

**Issue by penelopeysm** [TuringLang/docs#536]
The `_freeze` folder is cached in our current CI runs, but the cache isn't ever updated (because GitHub Actions is weird), meaning that only the first run with a given Manifest file is cached. This means that any time a page is changed it will be rerun on every subsequent CI run, which can take a long time.

julia-actions/cache gets around this by using the GitHub API to delete a cache before trying to save it. We should probably try to do something similar.

https://github.com/julia-actions/cache/blob/824243901fb567ccb490b0d0e2483ccecde46834/action.yml#L173-L184

**Comment by penelopeysm** [comment]
Actually a simpler alternative would be to append the hash of the docs folder itself to the cache key. Then use a restore key that doesn't include that hash, which will use the most recent cache.

**Comment by Gauravsinghrajputt** [comment]
Assign me for this issue
