### ISSUE TITLE
`docs` compilation time is too much for minor changes

### ISSUE THREAD

**Issue by shravanngoswamii** [TuringLang/docs#543]
I was trying to preview docs after a very long time, it's taking hours to run all docs and I don't think it's worth waiting for this much time if someone just want to make a minor change! Is there any way we can shorten this time?

A bit of a manual approach, but I guess we can save the `_freeze` directory of latest commit from `master` branch somewhere (maybe in another branch or repo) and give option to contributors to download and put it in their `docs` folder locally. Maybe we can use submodules for this...!

cc @penelopeysm!

**Comment by penelopeysm** [comment]
> I was trying to preview docs after a very long time, it's taking hours to run all docs

Do you mean locally?

**Comment by shravanngoswamii** [comment]
> Do you mean locally?

Yes!

**Comment by penelopeysm** [comment]
I never really found a good solution for that :( apart from:

1. `quarto render`-ing individual QMD files
2. just letting my computer run everything while I went to sleep / lunch / meetings

The _freeze folder on my local checkout is 50 MB large, so I don't think we should be committing that to the repo. But perhaps we could manually create a release containing a zipped _freeze directory when the Manifest is changed? (_freeze is only valid for a particular Manifest) I think this should be easy enough to do with a GitHub action that is run on workflow_dispatch, it just needs to checkout the master branch, build the docs, then create a release with _freeze + the Manifest

Do you know if _freeze is OS-independent?

**Comment by shravanngoswamii** [comment]
> just letting my computer run everything while I went to sleep / lunch / meetings

I did this yesterday and when I saw my laptop after like 4–5 hours, it was still stuck at 1st notebook, maybe there was some other issue! 

> Do you know if _freeze is OS-independent?

Most probably, it should be OS-independent because it only contains `JSON` and `Javascript` files!

**Comment by penelopeysm** [comment]
Let's at least try it :)
