### ISSUE TITLE
Dead links in Developer Tutorials

### ISSUE THREAD

**Issue by ajinkya-k** [TuringLang/docs#554]
Hello! 

There are a few dead links in the section [Developers  > DynamicPPL in Depth >  Mini Turing Implementation II: Contexts](https://turinglang.org/docs/tutorials/16-contexts/). 

Specifically, the link to the Mini Turing section points to what looks like an old link: https://turinglang.org/docs/tutorials/16-contexts/tutorial/14-minituring
I think it should point to https://turinglang.org/docs/tutorials/14-minituring/

**Comment by penelopeysm** [comment]
Thanks for reporting @ajinkya-k! This will be fixed in a few minutes once #555 is deployed.
