### ISSUE TITLE
Path to Julia 1.11

### ISSUE THREAD

**Issue by penelopeysm** [TuringLang/docs#560]
- [x] Update Manifest, make sure to run with Julia 1.11
   - [x] Dependency resolution failed offline because Pathfinder.jl doesn't yet have a version compatible with Turing 0.35. I bumped the compat entry on a local clone of Pathfinder, which allowed dependencies to be successfully resolved (which implies that there aren't any other packages that also have conflicting dependency resolution). I opened https://github.com/mlcolab/Pathfinder.jl/pull/214; when this is merged and released we can update the deps.
   - [x] Precompilation failed. https://github.com/TuringLang/Bijectors.jl/pull/337 should fix it. Get this merged and released.
       - [x] Bump Bijectors compat on Turing https://github.com/TuringLang/Turing.jl/pull/2384
           - [x] Bump Bijectors compat on AdvancedVI https://github.com/TuringLang/AdvancedVI.jl/pull/136
           - [x] Bump Bijectors compat on DynamicPPL https://github.com/TuringLang/DynamicPPL.jl/pull/701
               - [x] Get DynamicPPL CI passing with Turing
       - [x] Make Bijectors compatible with Enzyme 0.13 https://github.com/TuringLang/Bijectors.jl/pull/350 This is necessary because AdvancedVI requires Enzyme 0.13.

**Comment by penelopeysm** [comment]
SciMLSensitivity has Enzyme as a strong dep (so this is the downside of having a single environment for docs, #497).

**Comment by ChrisRackauckas** [comment]
> SciMLSensitivity has Enzyme as a strong dep (so this is the downside of having a single environment for docs, https://github.com/TuringLang/docs/pull/497).

> Let's hope that SciMLSensitivity can move towards package extension to support autograd libraries.

Why do you think that would solve the problem? Even if we did have extensions, Enzyme would still be a strong dep, right? I don't understand the logic here. There's no way to call into Enzyme automatically if it's not made a dep.
